### PR TITLE
Added the brilliant masterpiece that is the tako taco recipe; closes #3

### LINKED ISSUE #3: tako tacos
tacos with takos (squid)

brilliant

this must be implemented as soon as possible

### PR DESCRIPTION
**Pull request by IlkkaR-aalto**

### CODE REVIEW

**Comment by harivyasi** [comment]
Can you provide a description file.

**Comment by IlkkaR-aalto** [comment]
Added a description file and fixed a little mistake.

**Comment by harivyasi** [comment]
I would like to demonstrate that this new file appeared has appeared with a new commit. Would it be okay if I don't accept your PR just yet?

**Comment by IlkkaR-aalto** [comment]
Sure thing, demonstrate away~

**Comment by harivyasi** [comment]
Just to demonstrate: not accepting

**Comment by iojeda71** [comment]
Add it :)

**Comment by harivyasi** [comment]
The higher powers have spoken. Done :)

**Pull request merged**
